# Generated by Django 6.0.7 on 2026-07-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bolg_poster',
            new_name='blog_poster',
        ),
    ]
